apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug
        image: ubuntu
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y iproute2 iputils-ping dnsutils telnet && \
          /bin/bash
        stdin: true
        tty: true
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: debug
