[tools]
aws-cli = "latest"
helm = "latest"
helm-diff = "latest"
kubectl = "latest"
bitwarden = "latest"
jq = "latest"
gitversion = "5.12.0"
opentofu = "latest"
flux2 = "latest"
k9s = "latest"
go = "1.25.5"
air = "latest"
k6 = "latest"
golangci-lint = "latest"
